server:
    port: 8100
zuul:
    routes:
        doctors-service:
            url: http://localhost:8082
        deseases-service:
            url: http://localhost:8081
        patients-service:
            url: http://localhost:8083
    host:
        connect-timeout-millis: 2000
        socket-timeout-millis: 5000

management:
    endpoints:
        web:
            exposure:
                include: '*'
#    endpoint:
#        health:
#            show-details: ALWAYS